#!/bin/bash

if [ ! -d ~/hinkle_credentials ]; then
	git clone git@g.securly.com:davidhinkle/credentials.git	~/hinkle_credentials 2> /dev/null 1> /dev/null
fi

if [ "$1" == "PROD" ]; then
	gpg -q -o- ~/hinkle_credentials/hinkleawscli-prod.pgp 2> /dev/null
else	
	gpg -q -o- ~/hinkle_credentials/hinkleawscli-eng.pgp 2> /dev/null
fi
killall gpg-agent
